import type { Metadata } from "next";
import "./global.scss";
import Navbar from "@/components/Navbar";
import { unstable_setRequestLocale } from "next-intl/server";
import { locales } from "@/navigation";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LocaleLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string }
}>) {
  unstable_setRequestLocale(locale);

  return (
    <html>
      <body className={`flex flex-col min-h-dvh`}>
        <AppRouterCacheProvider>
          <Navbar />
          <main className="flex justify-center flex-1">
            <div className="container flex-1 flex flex-col">
              {children}
            </div>
          </main>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}